ahmetDev7/projecthr

- api/Controllers/ShipmentsController.cs
- api/Rest/Shipments/.rest
- api/Validators/ShipmentValidator.cs
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-79
Het is nu mogelijk om een shipment op te halen op basis van ID.
1. Zie rest file en voer de request uit
> Infscp01 79 get by id shipment

- api/Controllers/ShipmentsController.cs
- api/Rest/Shipments/.rest
- api/Validators/ShipmentValidator.cs
- api/models/ShipmentItem.cs
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-77
Er wordt hier de nieuwe functionaliteit voor Shipment toegevoegd: GetAll shipments.
1. Zie REST file van Shipments
> feature(shipment): Get All Shipments functionality

- api/Controllers/ShipmentsController.cs
- api/Rest/Shipments/.rest
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-88
Het is nu mogelijk om een specifieke shipment te verwijderen.
1. Voer een shipment met ID bij de rest file bij DELETE
2. Voer de request uit en check DB of het verwijderd is
> Infscp01 88 feature delete shipment

- api/Controllers/OrderController.cs
- api/Program.cs
- api/REST/Orders/.rest
- api/contexts/AppDbContext.cs
- api/providers/OrderProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-108
opzoeken by id werkt 
.rest file
n.v.t.
branch | PR
n.v.t.
> Infscp01 108 feature order get by

- api/Rest/Location.rest
- api/providers/LocationsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-182
De Put had een PATCH functionaliteit maar nu werkt het als een PUT
je kan de rest file gebruiken
n.v.t.
branch | PR
n.v.t.
> Infscp01 182 fix put locations

- api/Controllers/OrderController.cs
- api/REST/Orders/.rest
- api/providers/OrderProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-191
Je kan nu alle items zien van een specifieke order.
.rest file
n.v.t.
branch | PR
n.v.t.
> Infscp01 191 feature orders get by id items

- api/Controllers/ShipmentsController.cs
- api/Program.cs
- api/contexts/AppDbContext.cs
https://project-hr.atlassian.net/browse/INFSCP01-198
"message" met succesful deleted is nu te zien wanneer je een shipment delete
1. Verwijder een shipment en check de response met "message"
> fix(shipment): added "message" to deleted response

- api/Controllers/OrderController.cs
- api/REST/Orders/.rest
- api/providers/OrderProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-85
Je kan nu een order updaten
.rest file
n.v.t.
branch | PR
n.v.t.
> Infscp01 85 feature order update

- api/Controllers/OrderController.cs
- api/REST/Orders/.rest
- api/providers/OrderProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-105
Je kan de alle orders zien door middel van de get all functie
Je kan de .rest file gebruiken.
n.v.t.
branch | PR
n.v.t.
> Infscp01 105 1 feature order get all

- api/Controllers/SuppliersController.cs
- api/DTOs/ContactDTO.cs
- api/DTOs/SupplierDTO.cs
- api/DTOs/WarehouseDTO.cs
- api/Program.cs
- api/Validators/ContactValidator.cs
- api/providers/ContactProvider.cs
- api/providers/WarehouseProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-211
A few sentences describing the overall goals of the pull request's commits.
Ik heb de .rest file van warehouse en suppliers getest.
n.v.t.
branch | PR
n.v.t.
> Infscp01 211 fix contact rework

- api/Controllers/SuppliersController.cs
- api/DTOs/AddressDTO.cs
- api/DTOs/SupplierDTO.cs
- api/DTOs/WarehouseDTO.cs
- api/Program.cs
- api/Validators/AddressValidator.cs
- api/providers/AddressProvider.cs
- api/providers/WarehouseProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-212
A few sentences describing the overall goals of the pull request's commits.
Steps to test
Ik heb de .rest file van warehouse en suppliers getest.
n.v.t.
branch | PR
n.v.t.
> Infscp01 212 fix address rework

- api/Rest/ItemGroups/.rest
- api/providers/ItemGroupProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-189
Zorgt ervoor dat de funcitonaliteit van de put niet als een patch is net als hiervoor
Voer de .rest file uit van ItemGroups zorg ervoor dat je meerdere combinaties test van de PUT request
n.v.t
branch | PR
n.v.t
> fix(ItemGroups): update implementation as put

- api/Controllers/ShipmentsController.cs
- api/Enums/ShipmentStatus.cs
- api/Rest/Shipments/.rest
- api/models/Shipment.cs
- api/models/ShipmentItem.cs
- api/providers/ShipmentProvider.cs
- docs/erd/v2.0.dbml
https://project-hr.atlassian.net/browse/INFSCP01-84
Update shipment is nu toegevoegd bij ShipmentProvider en ShipmentController. Er is ook een typefout in de enum opgelost. Ook is er een verandering toegepast in de Shipment Model vanwege een conversion error naar type int?.
1. Run de shipment update in het .REST bestand
> Infscp01 84 feature shipment update

- api/Controllers/ItemLinesController.cs
- api/REST/ItemLines/.rest
- api/providers/ItemLinesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-58
Het is nu mogelijk om een item line op te halen op basis van het id bij /itemlines/{id}
1. Run de GET by id in de .REST met de gegeven ID van de item line die je hebt in je DB bij item lines
> Infscp01 58 feature get item line by id

- api/Controllers/ItemLinesController.cs
- api/REST/ItemLines/.rest
- api/providers/ItemLinesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-22
Het is nu mogelijk om via de endpoint /itemlines alle item lines op te halen
1. Run de /itemlines in de item lines .rest bestand
> Infscp01 22 feature get all item lines

- api/Controllers/ItemLinesController.cs
- api/REST/ItemLines/.rest
- api/providers/ItemLinesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-23
Het is nu mogelijk om een item_line te updaten op basis van de gegeven id
1. Run de PUT request in de .REST file van item_lines met een ID van een item line die in je DB is.
2. Controleer de updated_at, de response en of het in de database updated wordt.
> Infscp01 23 feature update item line

- api/Controllers/InventoriesController.cs
- api/DTOs/InventoryDTO.cs
- api/Migrations/20241202115645_create_inventory_tbl_relating_to_location_and_item.Designer.cs
- api/Migrations/20241202115645_create_inventory_tbl_relating_to_location_and_item.cs
- api/Program.cs
- api/REST/Inventories.rest
- api/REST/Locations.rest
- api/Validators/InventoryLocationValidator.cs
- api/Validators/InventoryValidator.cs
- api/contexts/AppDbContext.cs
- api/models/Inventory.cs
- api/models/Item.cs
- api/models/Location.cs
- api/providers/InventoriesProvider.cs
- api/providers/LocationsProvider.cs
- api/utils/CollectionUtil.cs
- docs/erd/v2.1.dbml
https://project-hr.atlassian.net/browse/INFSCP01-18
Het aanmaken van een inventory.
1. Er zijn nieuwe migrations voer ze uit.
2. Je kunt de `Inventories.rest` file uitvoeren om te testen.
3. Check als je nog een inventory kan maken met de zelfde ItemId `(verwachte resultaat: error message)`
4. Check als je de zelfde inventory nogmaals kan opslaan op de zelfde Locatie `(verwachte resultaat: error message)`
5. Check in de inventory request met duplicate location_ids `(verwachte resultaat: error message)`
- https://github.com/ahmetDev7/projecthr/pull/83
branch | PR
------ | ------
Create Transfer| [link](https://github.com/ahmetDev7/projecthr/pull/83)
> Infscp01 18 feature create inventory

- api/Controllers/ItemLinesController.cs
- api/REST/ItemLines/.rest
- api/providers/ItemLinesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-24
Het is nu mogelijk om een item_line te deleten via een DELETE request naar /item_lines/{id}
1. Run de DELETE request in de .rest file van item_lines met een ID vanuit jouw DB
> Infscp01 24 feature delete item line

- api/Controllers/ClientsController.cs
- api/REST/Clients/Clients.rest
- api/providers/ClientsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-119
Je kan nu alle Client ophalen met behulp van /clients
1. Run de /cleints in de  .rest bestand
n.v.t.
> Infscp01 119 feature client get all

- api/Controllers/InventoriesController.cs
- api/DTOs/InventoryDTO.cs
- api/REST/Inventories.rest
- api/providers/InventoriesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-19
Get all inventories
1. Voer de `Inventories.rest` file uit waarbij je alle inventories ophaalt
n.v.t
branch | PR
n.v.t
> feature(Inventories): get all inventories

- api/Controllers/InventoriesController.cs
- api/REST/Inventories.rest
- api/providers/InventoriesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-74
Get single inventory by id
1. Voer de rest file uit van `Iventories.rest`
n.v.t
branch | PR
n.v.t
> feature(Inventories): Get single inventory by id

- api/Controllers/ItemTypesController.cs
- api/REST/ItemTypes/.rest
- api/providers/ItemTypesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-28
Het is nu mogelijk om alle item types op te halen met een GET functie
1. Run de GET functie uit van get all item types in de .REST file
> Infscp01 28 feature get all item types

- api/Controllers/InventoriesController.cs
- api/Migrations/20241202195842_on_delete_set_null_inventory_id_in_locations_tbl.Designer.cs
- api/Migrations/20241202195842_on_delete_set_null_inventory_id_in_locations_tbl.cs
- api/REST/Inventories.rest
- api/contexts/AppDbContext.cs
- api/models/Inventory.cs
- api/providers/InventoriesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-21
feature delete inventory
1. voer de rest file uit `Inventories.rest` met de delete action
n.v.t
branch | PR
n.v.t
> Infscp01 21 feature delete inventory

- api/Controllers/ItemTypesController.cs
- api/REST/ItemTypes/.rest
- api/providers/ItemTypesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-29
Het is nu mogelijk om een item type te updaten op basis van ID.
1. Run de UPDATE request met de item type id die je hebt in je DB in de .REST file
> Infscp01 29 feature update item type

- api/Controllers/ItemsController.cs
- api/Rest/Items/.rest
- api/providers/ItemsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-33
Het is nu mogelijk om een Item te updaten via de PUT methode naar /items/{item_id}
1. Run de PUT methode in de .REST file met een item_id die te vinden is in jouw DB.
> Infscp01 33 feature item update

- .github/workflows/dotnet.yml
https://project-hr.atlassian.net/browse/INFSCP01-205
In deze .yml file is er 1 trigger met 2 events: On push on main branch & On pull request to main branch.
Dit is gedaan dat als er een pull request wordt gemaakt naar main branch dat er direct wordt gebuild en getest en nadat het gemerged is en gepushed wordt nog een keer build & test. De tweede keer kan dat er bij het mergen een conflict veroorzaakt wordt na het resolven van conflicts dat het zeker op de main branch nog werkend is.
Vervolgens wordt een job uitgevoerd met meerdere steps.
Er is gekozen voor ubuntu vanwege dat het het minst resources verbruikt als runner ("runs-on").
Step 1: Bij de checkout wordt de code van de repository gehaald en in de workflow geplaatst.
Step 2: Dotnet wordt geinstalleerd met versie 8 waarop het C# …
> Create dotnet.yml (CI) for building and testing

- api/Controllers/ItemsController.cs
- api/Rest/Items/.rest
- api/providers/ItemsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-186
Get inventories for specific item
1. Create item
2. Create inventory
3.  Voer de `Items` rest file uit op basis van `{item_id}/inventories`
n.v.t
branch | PR
n.v.t
> feature(Inventories): Get inventories for specific item

- api/Controllers/ItemsController.cs
- api/Rest/Items/.rest
https://project-hr.atlassian.net/browse/INFSCP01-187
Get inventories totals based on item id
1. Create item
2. Create inventory
3.  Voer de `Items` rest file uit op basis van `{item_id}/inventories/totals`
n.v.t
branch | PR
n.v.t
> feature(Inventories): Get inventories totals based on item id

- api/Controllers/WarehouseController.cs
https://project-hr.atlassian.net/browse/INFSCP01-175
Het woord 'all' weghalen van de endpoint /warehouses
1. Voer de endpoint uit in de Warehouses .rest file met `/warehouses`
n.v.t
branch | PR
n.v.t
> fix(Warehouse): remove the word 'all' from endpoint

- api/Controllers/WarehousesController.cs
- api/REST/Locations.rest
- api/REST/Warehouses.rest
- api/providers/WarehouseProvider.cs
jira link
- https://project-hr.atlassian.net/browse/INFSCP01-177
De response voor de get locations for a specific warehouse is gefixed en werkt nu
1. Run the .restfile
> INFSCP01-177-fix-get-warehouse-locations-response

- api/Controllers/ClientsController.cs
- api/providers/ClientsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-121
Je kan nu een orders van een Client ophalen met behulp van /clients/clientid/orders
Je kan nu een Client ophalen met behulp van /clients/clientid/orders
Als je het programma runt dan kan je via swagger bij het kopje test het programma testen
n.v.t.
> Infscp01 121 1 feature client get orders

- api/Controllers/ContactsController.cs
- api/REST/Clients/Contacts.rest
https://project-hr.atlassian.net/browse/INFSCP01-272
Je kan nu een conact aanmaken met behulp van de post /contacts
1. Run de applicatie en gebruik de rest file /contacts
n.v.t.
> Infscp01 272 feature create contact

- api/Controllers/AddressesController.cs
- api/REST/Clients/Addreses.rest
- api/providers/AddressProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-278
Je kan nu een adres aanmaken met behulp van de post /addresses
1. Run de applicatie en gebruik de rest file /addresses
n.v.t
> Infscp01 278 feature create address

- api/Controllers/ContactsController.cs
- api/REST/Clients/Contacts.rest
- api/providers/ContactProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-273
Het is nu mogelijk om een Contact te updaten via de PUT methode naar /Contact/id
1.Run de PUT methode in de .REST file met een item_id die te vinden is in jouw DB.
n.v.t.
> Infscp01 273 feature update contact

- docs/erd/v3.dbml
n.v.t
warehouse log maak old en new value nullable
n.v.t
n.v.t
branch | PR
n.v.t
> docs: make log old and new value nullable

- api/Controllers/AddressesController.cs
- api/REST/Clients/Addresses.rest
https://project-hr.atlassian.net/browse/INFSCP01-282
Het is nu mogelijk om een address op te halen via de get methode.
1. Run de Get methode in de .REST file /Addresses.
n.vt.
> Infscp01 282 get all addresses

- api/Controllers/TransfersController.cs
- api/REST/Transfers.rest
- api/providers/TransfersProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-17
Delete transfer
1. Voer de rest file uit om een transfer te delete `Transfers.rest`
n.v.t
branch | PR
n.v.t
> feature(Transfers): delete transfer

- .github/workflows/dotnet.yml
https://project-hr.atlassian.net/browse/INFSCP01-321
Add Coverage Report to Summary
n.v.t
n.v.t
branch | PR
n.v.t
> feature(workflow): Add Coverage Report to Summary

- api/Controllers/InventoriesController.cs
- api/Controllers/ItemsController.cs
- api/DTOs/InventoryDTO.cs
- api/Migrations/20241224222724_remove_inventory_from_location.Designer.cs
- api/Migrations/20241224222724_remove_inventory_from_location.cs
- api/Migrations/20241224235506_update_tbl_inventory_calculated_fields.Designer.cs
- api/Migrations/20241224235506_update_tbl_inventory_calculated_fields.cs
- api/Migrations/20241225210217_create_mtm_tbl_inventory_location.Designer.cs
- api/Migrations/20241225210217_create_mtm_tbl_inventory_location.cs
- api/Migrations/20241231185539_update_tbl_locations_remove_column_on_hand.Designer.cs
- api/Migrations/20241231185539_update_tbl_locations_remove_column_on_hand.cs
- api/Migrations/20250104222101_update_tbl_inventory_allocated_total.Designer.cs
- api/Migrations/20250104222101_update_tbl_inventory_allocated_total.cs
- api/Program.cs
- api/Validators/TransferValidator.cs
- api/contexts/AppDbContext.cs
- api/models/Inventory.cs
- api/models/InventoryLocation.cs
- api/models/Location.cs
- api/providers/InventoriesProvider.cs
- api/providers/LocationsProvider.cs
- api/providers/TransfersProvider.cs
- docs/UML/CargoHub-Class-Diagram.txt
- docs/erd/v3.dbml
> [!CAUTION]
> Deze PR bevat BREAKING CHANGES 
https://project-hr.atlassian.net/browse/INFSCP01-325
Alles in relatie met inventory is aangepast zodat het mogelijk is om op één location meerdere items te plaatsen, en dit wordt nu ook weergegeven in de response. Daarnaast zijn de berekeningen van calculated values veranderd: in plaats van deze bij elke request opnieuw uit te rekenen, worden de waarden nu opgeslagen in de database. Wanneer er een verandering plaatsvindt die invloed heeft op deze variabelen, worden ze automatisch geüpdatet.
1. Voer de nieuwe migrations uit.
2. Maak meerdere items en locations aan via de rest files.
3. Maak een nieuwe inventory
4. Check als de response de juiste hoeveelheden en warehouse informatie goed toont
5. Update de inventory en check de response
6. …
> Infscp01 325 fix locations multiple items

- api/Controllers/WarehousesController.cs
- api/DTOs/DockDTO.cs
- api/REST/Warehouses.rest
- api/providers/WarehousesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-329
Van een specifieke warehouse dock informatie ophalen met de dock items
1. Voer de Warehouses.rest file uit met de endpoint /docks
n.v.t
branch | PR
n.v.t
> feature(WarehouseDock): warehouse_id/dock endpoint

- api/Controllers/WarehousesController.cs
- api/DTOs/WarehouseDTO.cs
- api/Migrations/20250107152841_create_tbl_mtm_warehouse_contact.Designer.cs
- api/Migrations/20250107152841_create_tbl_mtm_warehouse_contact.cs
- api/Program.cs
- api/REST/Warehouses.rest
- api/Validators/WarehouseRequestValidator.cs
- api/Validators/WarehouseValidator.cs
- api/contexts/AppDbContext.cs
- api/models/Contact.cs
- api/models/Warehouse.cs
- api/models/WarehouseContact.cs
- api/providers/ContactProvider.cs
- api/providers/WarehousesProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-324
Warehouses kunnen nu meerdere contacten bevatten. Waarbij nu ook te zien is welke functie elk contactpersoon heeft.
1.  Voer de migrations uit.
2.  Voer alle endpoints uit van `Warehouses.rest` file
3. Probeer een contact te verwijderen terwijl er een relatie is met een warehouse. [Dit moet een error melding geven]
n.v.t
branch | PR
n.v.t
> Infscp01 324 fix many to many warehouse contacts

- .github/workflows/dotnet.yml
- api/Program.cs
https://project-hr.atlassian.net/browse/INFSCP01-242
Integration Tests zijn toegevoegd aan de CI pipeline. En Unit Tests & Integration Tests zijn gesplitst.
1.  Run the pipeline
> feature(CI pipeline): Added Integration Tests to CI pipeline

- api.IntegrationTests/IntegrationTestsItem.cs
- api.IntegrationTests/Seeding.cs
Jira Link
https://project-hr.atlassian.net/browse/INFSCP01-254
Ik heb 2 Integratie tests geschreven voor Items
> feature(IntegrationTestsItem) Ik heb integratie tests gemaakt voor Items 

- api.IntegrationTests/ClientsIntegrationTests.cs
- api.IntegrationTests/Seeding.cs
Jira Link
https://project-hr.atlassian.net/browse/INFSCP01-253
Ik heb integratietesten geschreven voor client, zodat onze test coverage breder is
1. dotnet test
> INFSCP01-253-feature-Integration-test-Clients

- api.IntegrationTests/ItemTypesIntegrationTests.cs
https://project-hr.atlassian.net/browse/INFSCP01-341
Added Item Type Update Test & Item Type Delete Test
> feature(integration tests): Added Item Type Update Test & Item Type Delete Test

- api/Controllers/ShipmentsController.cs
- api/REST/Shipments.rest
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-81
Get items van een specefieke shipment
1. Voer de `Shipments.rest` file uit met de endpoint shipments/{id}/items
n.v.t
branch | PR
n.v.t
> feature(shipment): get items by shipment endpoint

- api.IntegrationTests/ItemGroupsIntegrationTests.cs
- api.IntegrationTests/Seeding.cs
https://project-hr.atlassian.net/browse/INFSCP01-260
Added Integration tests for Item Groups: Get All, Get By Id, Get All Related Items, Create, Update and Delete.
> feature(integration tests): Added Item Groups Integration Tests

- api/Controllers/ShipmentsController.cs
- api/DTOs/shipment/ShipmentDTO.cs
- api/Program.cs
- api/REST/Shipments.rest
- api/Validators/ShipmentItemRequestValidator.cs
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-200
Bij een specifieke shipment kan je de shipment items vervangen.
1. Voer de rest file uit `Shipments` met de endpoint shipments/{id}/items
2. Probeer items toe tevoegen die bijvoorbeeld niet bij de gerelateerde order horen.
n.v.t
branch | PR
n.v.t
> feature(shipment):  update assigned items to a specific shipment

- api.Tests/UnitTest2.cs
- api.Tests/UnitTest3.cs
- api.Tests/UnitTest4.cs
- api.Tests/UnitTest5.cs
- api.Tests/UnitTest6.cs
- api.Tests/UnitTest7.cs
- api.Tests/UnitTest8.cs
- api/api.csproj
https://project-hr.atlassian.net/browse/INFSCP01-224
UnitTests gemaakt. 
1. run de applicatie met dotnet test
> Infscp01 297 unit test

- api/Controllers/ItemsController.cs
- api/REST/Items.rest
- api/providers/ItemsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-34
Items kunnen nu verwijderd worden. Hierbij wordt er ook rekening gehouden met de bijbehorende relaties zoals:
- ShipmentItems
- OrderItems
- TransferItems
- Inventories
- DockItems
1. Voer de rest file uit `Items.rest` roep hierbij de /delete endpoint aan.
n.v.t
branch | PR
n.v.t
> feature(item): delete implementation with relation validation

- .github/workflows/dotnet.yml
- api.IntegrationTests/ClientsIntegrationTests.cs
- api.IntegrationTests/Seeding.cs
https://project-hr.atlassian.net/browse/INFSCP01-253
Added Get All Related Orders, Create, Update and Delete integration tests. Also added API KEY structure with ENV json.
> feature(client integration tests)

- api.IntegrationTests/ItemGroupsIntegrationTests.cs
- api/Controllers/ItemGroupsController.cs
https://project-hr.atlassian.net/browse/INFSCP01-260
Added authorization to item groups test
> Infscp01 260 feature integration tests item groups

- api/Controllers/InventoriesController.cs
- api/Controllers/ItemLinesController.cs
- api/Controllers/ItemTypesController.cs
- api/Controllers/ItemsController.cs
- api/Controllers/LocationsController.cs
- api/Controllers/OrderController.cs
- api/Controllers/ShipmentsController.cs
- api/Controllers/SuppliersController.cs
- api/Controllers/TransfersController.cs
- api/Controllers/WarehousesController.cs
https://project-hr.atlassian.net/browse/INFSCP01-288
Added all Authorization headers based on table of PO on endpoints
1. Run api keys on endpoints
> Infscp01 288 feature auth roles on endpoints

- api.IntegrationTests/AddressesIntegrationTests.cs
- api.IntegrationTests/ItemIntegrationTests.cs
- api.IntegrationTests/ItemTypesIntegrationTests.cs
- api.IntegrationTests/LocationIntegrationTests.cs
- api.IntegrationTests/ShipmentIntegrationTests.cs
- api.IntegrationTests/SuppliersIntegrationTest.cs
- api.IntegrationTests/WarehousesIntegrationTests.cs
https://project-hr.atlassian.net/browse/INFSCP01-257
Created integration tests for Addresses
> Infscp01 257 feature integration test addresses

- api.IntegrationTests/ContactsIntegrationTests.cs
https://project-hr.atlassian.net/browse/INFSCP01-258
Added Contact integration tests
> Infscp01 258 feature integration test contacts

- api/Validators/OrderRequestValidator.cs
- api/Validators/ShipmentRequestValidator.cs
- api/Validators/ShipmentValidator.cs
- api/providers/InventoriesProvider.cs
- api/providers/OrderProvider.cs
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-322
Process inventory calculation.
1. Maak een order aan
2. Maak een shipment aan
3. Commit een shipment
4. Commit order
5. Check de inventory waardes op basis van de condities van de calculatie (Hierbij moeten we samen zitten)
n.v.t
branch | PR
n.v.t
> Infscp01 322 feature inventory calculation

- api.IntegrationTests/Seeding.cs
- api.IntegrationTests/TransfersIntegrationTests.cs
https://project-hr.atlassian.net/browse/INFSCP01-262
Create integration test transfers
`dotnet test` uitvoeren
n.v.t
branch | PR
n.v.t
> feature(IntegrationTest): create transfers integration test

- api.IntegrationTests/InventoriesIntegrationTests.cs
- api.IntegrationTests/Seeding.cs
https://project-hr.atlassian.net/browse/INFSCP01-263
Created Inventory integration tests
> feature(IntegrationTest): create inventory integration test

- api/Controllers/ItemsController.cs
- api/DTOs/item/ItemDTO.cs
- api/Migrations/20250115085441_update_items_tbl_created_by.Designer.cs
- api/Migrations/20250115085441_update_items_tbl_created_by.cs
- api/REST/Items.rest
- api/REST/Suppliers.rest
- api/models/Item.cs
- api/providers/ItemsProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-286
Het is nu mogelijk om de "created_by" te zien bij de Item endpoint
1. Run de Item endpoints en check voor de "created_by"
> feature(item): create item with created_by role

- api/Controllers/ShipmentsController.cs
- api/DTOs/shipment/ShipmentDTO.cs
- api/Migrations/20250115091653_update_tbl_shipments_created_by.Designer.cs
- api/Migrations/20250115091653_update_tbl_shipments_created_by.cs
- api/models/Shipment.cs
- api/providers/ShipmentProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-285
Nu bij shipments zie je "created_by" met de aangegeven rol
1. Run de shipment endpoints in de rest file en check "created_by"
> feature(Shipments): Added Created By logging

- api/Controllers/OrderController.cs
- api/DTOs/item/OrderDTO.cs
- api/Migrations/20250115091305_update_orders_tbl_created_by.Designer.cs
- api/Migrations/20250115091305_update_orders_tbl_created_by.cs
- api/REST/Clients.rest
- api/REST/Inventories.rest
- api/REST/Locations.rest
- api/REST/Orders.rest
- api/REST/Warehouses.rest
- api/models/Order.cs
- api/providers/OrderProvider.cs
https://project-hr.atlassian.net/browse/INFSCP01-284
Bij Orders zie je "created_by" met de aangegeven rol
1. Run de orders endpoints in de rest file en check "created_by"
> feature(item): create order with created_by role

- .github/workflows/dotnet.yml
- api.Tests/UnitTest2.cs
- api.Tests/UnitTest3.cs
- api.Tests/UnitTest4.cs
- api.Tests/UnitTest5.cs
- api.Tests/UnitTest6.cs
- api.Tests/UnitTest8.cs
- api/DTOs/item/ItemDTO.cs
- api/models/Item.cs
- api/models/Order.cs
- api/models/Shipment.cs
- api/providers/OrderProvider.cs
- api/providers/ShipmentProvider.cs
- api/utils/DateUtil.cs
- api/utils/NumberUtil.cs
Fix: Added Unit Testing class filters to CI pipeline
> fix: Added unit testing class filters to CI pipeline

- .github/workflows/dotnet.yml
Added API keys with secrets to the pipeline so it can be used whenever a integration test is made with a specific key.
1. Run the pipeline
> feature(CI): Added API Keys Secrets to integration tests

- api.IntegrationTests/AddressesIntegrationTests.cs
- api.IntegrationTests/ClientsIntegrationTests.cs
- api.IntegrationTests/ContactsIntegrationTests.cs
- api.IntegrationTests/InventoriesIntegrationTests.cs
- api.IntegrationTests/ItemGroupsIntegrationTests.cs
- api.IntegrationTests/ItemIntegrationTests.cs
- api.IntegrationTests/ItemLinesIntegrationTests.cs
- api.IntegrationTests/ItemTypesIntegrationTests.cs
- api.IntegrationTests/LocationIntegrationTests.cs
- api.IntegrationTests/OrdersIntegrationTests.cs
- api.IntegrationTests/ShipmentIntegrationTests.cs
- api.IntegrationTests/SuppliersIntegrationTest.cs
- api.IntegrationTests/TransfersIntegrationTests.cs
- api.IntegrationTests/WarehousesIntegrationTests.cs
> test(Shipment): implement edge cases
